title: "Affordability Act"
description: "Community-drafted model-law to tie housing, land, vehicle & insurance pricing to wages and real conditions."
url: "https://www.affordact.com"
baseurl: ""

author:
  name: Caleb “Elite” Ferguson
  url: https://github.com/cFerg
  email: mrcalebf@gmail.com

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
timezone: America/New_York

include:
  - assets
  - policy
  - tools
  - sections.json

exclude:
  - README.md
  - LICENSE
  - LICENSE-CODE
  - .github
  - .gitignore
  - .gitattributes
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "policy/sections"
    values:
      layout: default

plugins: []
